// src/data/CompanyData.js
export const companies = [
  {
    id: 1,
    name: "Vision Academy",
    description: "Leading school offering quality education.",
    address: "Gerji, Addis Ababa",
    phone: "011 647 7418",
    website: "http://www.visionacademy.com",
    facebook: "https://www.facebook.com/VisionAcademy",
    telegram: "https://t.me/VisionAcademy",
    tiktok: "https://www.tiktok.com/@VisionAcademy",
    instagram: "https://www.instagram.com/VisionAcademy",
    category: "schools",
  },
  {
    id: 2,
    name: "School of Tomorrow - Bole Michael",
    description:
      "A branch of School of Tomorrow providing excellent education.",
    address: "Bole Michael, Addis Ababa",
    phone: "011 662 6695",
    website: "http://www.schooloftomorrow.com",
    category: "schools",
  },
  {
    id: 3,
    name: "School of Tomorrow - Bisrate Gabriel",
    description:
      "Another branch of School of Tomorrow, known for its academic excellence.",
    address: "Bisrate Gabriel, Addis Ababa",
    phone: "011 618 5431",
    website: "http://www.schooloftomorrow.com",
    category: "schools",
  },
  {
    id: 4,
    name: "School of Tomorrow - CMC",
    description: "The CMC branch of School of Tomorrow.",
    address: "CMC, Addis Ababa",
    phone: "011-5-15-96-73",
    website: "http://www.schooloftomorrow.com",
    category: "schools",
  },
  {
    id: 5,
    name: "School of Tomorrow - Lem",
    description: "Lem branch of School of Tomorrow offering modern education.",
    address: "Lem, Addis Ababa",
    phone: "011 663 1910",
    website: "http://www.schooloftomorrow.com",
    category: "schools",
  },
  {
    id: 6,
    name: "Ethio-Parents-School - Gerji",
    description: "Gerji branch of Ethio-Parents-School.",
    address: "Gerji, Addis Ababa",
    phone: "+251 116 293473",
    website: "http://www.ethioparentschool.com",
    category: "schools",
  },
  {
    id: 7,
    name: "Ethio-Parents-School - Gullele",
    description: "Gullele branch of Ethio-Parents-School.",
    address: "Gullele, Addis Ababa",
    phone: "0112 593747",
    website: "http://www.ethioparentschool.com",
    category: "schools",
  },
  {
    id: 8,
    name: "Sandford International School",
    description: "Prestigious international school in Addis Ababa.",
    address: "Kebena, Addis Ababa",
    phone: "011 123 3726",
    website: "http://www.sandfordschool.com",
    category: "schools",
  },
  {
    id: 9,
    name: "Nazareth School",
    description: "Historic school located in 4 Kilo, Addis Ababa.",
    address: "4 Kilo, Addis Ababa",
    phone: "011 629 8601",
    website: "http://www.nazarethschool.com",
    category: "schools",
  },
  {
    id: 10,
    name: "Fountain of Knowledge School",
    description: "Educational institution in CMC, Addis Ababa.",
    address: "CMC, Addis Ababa",
    phone: "011 645 4919",
    website: "http://www.fountainofknowledge.com",
    category: "schools",
  },
  {
    id: 11,
    name: "Yod Abyssinia Traditional Restaurant",
    description:
      "Traditional Ethiopian restaurant offering cultural experiences.",
    address: "Bole, Addis Ababa",
    phone: "011 661 2985",
    website: "http://www.yodabyssinia.com",
    category: "restaurants",
  },
  {
    id: 12,
    name: "Sapore Restaurant",
    description: "Italian restaurant in Bole Japan, Addis Ababa.",
    address: "Bole Japan, Addis Ababa",
    phone: "091 143 9712",
    website: "http://www.saporerestaurant.com",
    category: "restaurants",
  },
  {
    id: 13,
    name: "Marcus Addis Restaurant & Sky Bar",
    description: "Modern restaurant and sky bar in Mexico, Addis Ababa.",
    address: "Mexico, Addis Ababa",
    phone: "094 511 1111",
    website: "http://www.marcusaddis.com",
    category: "restaurants",
  },
  {
    id: 14,
    name: "Golden Plate Restaurant",
    description: "Fine dining restaurant in Bole, Addis Ababa.",
    address: "Bole, Addis Ababa",
    phone: "097 574 5252",
    website: "http://www.goldenplate.com",
    category: "restaurants",
  },
  {
    id: 15,
    name: "La Nouvelle Cafe & Restaurant",
    description: "Charming cafe and restaurant in Bole, Addis Ababa.",
    address: "Bole, Addis Ababa",
    phone: "092 993 0200",
    website: "http://www.lanouvelle.com",
    category: "restaurants",
  },
  {
    id: 16,
    name: "Lancet Specialized Internal Medicine and Surgical Center",
    description: "Specialized medical center in Megenaega, Addis Ababa.",
    address: "Megenaega, Addis Ababa",
    phone: "097 771 7171",
    website: "http://www.lancetmed.com",
    category: "hospitals",
  },
  {
    id: 17,
    name: "Kadisco General Hospital",
    description: "Full-service general hospital in Gerji Giorgis, Addis Ababa.",
    address: "Gerji Giorgis, Addis Ababa",
    phone: "011 629 8902",
    website: "http://www.kadiscohospital.com",
    category: "hospitals",
  },
  {
    id: 18,
    name: "Hallelujah General Hospital",
    description: "General hospital in Gotera, Addis Ababa.",
    address: "Gotera, Addis Ababa",
    phone: "011 470 4242",
    website: "http://www.hallelujahhospital.com",
    category: "hospitals",
  },
  {
    id: 19,
    name: "Washington Medical Center",
    description: "Modern medical center in Bole Rwanda, Addis Ababa.",
    address: "Bole Rwanda, Addis Ababa",
    phone: "011 663 5969",
    website: "http://www.washingtonmed.com",
    category: "hospitals",
  },
  {
    id: 20,
    name: "Nordic Medical Centre",
    description: "Nordic healthcare services in Bole, Addis Ababa.",
    address: "Bole, Addis Ababa",
    phone: "092 910 5653",
    website: "http://www.nordicmedical.com",
    category: "hospitals",
  },
  {
    id: 21,
    name: "Landmark General Hospital",
    description: "General hospital located in Mexico, Addis Ababa.",
    address: "Mexico, Addis Ababa",
    phone: "011 552 5719",
    website: "http://www.landmarkhospital.com",
    category: "hospitals",
  },
  {
    id: 22,
    name: "City Medical Clinic",
    description:
      "A well-equipped clinic providing a range of medical services.",
    address: "Kazanchis, Addis Ababa",
    phone: "011 554 8825",
    website: "http://www.citymedicalclinic.com",
    category: "clinics",
  },
  {
    id: 23,
    name: "Addis Dental Clinic",
    description: "Specialized dental care and oral surgery services.",
    address: "Megenagna, Addis Ababa",
    phone: "011 662 3300",
    website: "http://www.addisdentalclinic.com",
    category: "clinics",
  },
  {
    id: 24,
    name: "Teklehaymanot Clinic",
    description: "General medical services and emergency care.",
    address: "Arat Kilo, Addis Ababa",
    phone: "011 111 2345",
    website: "http://www.teklehaymanotclinic.com",
    category: "clinics",
  },
  {
    id: 25,
    name: "Green Life Spa & Wellness Center",
    description: "Relaxation and rejuvenation services.",
    address: "Bole, Addis Ababa",
    phone: "091 234 5678",
    website: "http://www.greenlifespa.com",
    category: "wellness",
  },
  {
    id: 26,
    name: "Fit Club Gym",
    description: "A modern fitness center offering various workout programs.",
    address: "Sarbet, Addis Ababa",
    phone: "091 876 5432",
    website: "http://www.fitclubgym.com",
    category: "fitness",
  },
  {
    id: 27,
    name: "Elite Beauty Salon",
    description: "Professional beauty and hair care services.",
    address: "Piazza, Addis Ababa",
    phone: "091 543 2100",
    website: "http://www.elitebeautysalon.com",
    category: "salons",
  },
  {
    id: 28,
    name: "Rainbow Childcare",
    description: "Safe and nurturing childcare services.",
    address: "Gurd Shola, Addis Ababa",
    phone: "011 678 9012",
    website: "http://www.rainbowchildcare.com",
    category: "childcare",
  },
  {
    id: 29,
    name: "TechHub Solutions",
    description: "IT services and solutions provider.",
    address: "Bole, Addis Ababa",
    phone: "091 345 6789",
    website: "http://www.techhubsolutions.com",
    category: "it services",
  },
  {
    id: 30,
    name: "Creative Minds Design Studio",
    description: "Graphic design and branding services.",
    address: "Kazanchis, Addis Ababa",
    phone: "091 567 8901",
    website: "http://www.creativemindsdesign.com",
    category: "design",
  },
  {
    id: 31,
    name: "Blue Nile Tours",
    description: "Tourism services and travel agency.",
    address: "Meskel Square, Addis Ababa",
    phone: "011 555 5678",
    website: "http://www.blueniletours.com",
    category: "travel",
  },
  {
    id: 32,
    name: "Ethio Telecom",
    description: "Telecommunications provider in Ethiopia.",
    address: "Churchill Road, Addis Ababa",
    phone: "011 550 4444",
    website: "http://www.ethiotelecom.et",
    category: "telecom",
  },
  {
    id: 33,
    name: "Awash Bank",
    description: "One of Ethiopia's leading banks.",
    address: "Arat Kilo, Addis Ababa",
    phone: "011 156 7890",
    website: "http://www.awashbank.com",
    category: "banking",
  },
  {
    id: 34,
    name: "Dashen Bank",
    description: "Commercial bank offering various financial services.",
    address: "Bole, Addis Ababa",
    phone: "011 123 4567",
    website: "http://www.dashenbank.com",
    category: "banking",
  },
  {
    id: 35,
    name: "Your Website Name",
    description: "A brief description of your website's services.",
    address: "Your City, Your Country",
    phone: "Your Phone Number",
    website: "http://www.yourwebsite.com",
    category: "services",
  },
];
